"""One-shot script to inject 8 manual-add cards into startups-data.js. Delete after use."""
import re

NEW_ENTRIES = r'''  {slug: "jentic", bgTeam: ["Greens"], name: "Jentic", url: "https://jentic.com/", oneliner: "POC partner for the Agent Orchestration cell with thesis BG Score 95. Arazzo workflows + agentic sandboxes + centralised credentials + governed execution — the architectural pattern for routing, scheduling, and governing multi-agent workflows in a regulated environment, built compliance-native by default. Dublin-based; pre-seed $4.5M.", gap: "P1 — Agent Orchestration", stage: "Pre-Seed — $4.5M", geo: "Dublin, Ireland", finserv: "POC partner status with BG per the thesis Gap Map (Jentic, BG Score 95). Dublin HQ places the company inside the European compliance-native architecture lane. Arazzo workflow pattern is the open-standard approach to agent orchestration. Highest score on any P1 candidate.", team: "Team profile not deeply public-facing in cycle-14 search; the thesis-level reference indicates the architecture and POC fit are what's been validated. Investors: Pre-seed $4.5M.", thesis: "Canonical thesis match for P1 Agent Orchestration. The system already understands what good looks like in this cell — Jentic is what set the bar. Conversion from kanban manual-add (Dave, 2026-05-05, accepted) to formal pipeline card is the operational tidy-up — the thesis has named Jentic at BG Score 95 since cycle 7. Watch-item: does the POC progress from architecture validation into something that anchors the broader marketplace governance plane, or does it stay as a single-customer engagement?", evidence: [["Jentic — official site", "https://jentic.com/"], ["Thesis Gap Map — Agent Orchestration POC Partner", "https://github.com/dpowert2/Bene_Gesserit/blob/main/config/thesis.md"]], score: 95, bars: {gap: [35, 35], finserv: [22, 25], stage: [20, 20], team: [18, 20]}},
  {slug: "gradient-labs", bgTeam: ["Greens"], name: "Gradient Labs", url: "https://gradient-labs.ai/", oneliner: "SOP-following agents deployed in regulated banking. Procedure-based, auditable, deterministic — the architectural pattern the thesis names as the template for how agents should behave inside the walled garden. Series A $13M; deployed at a major UK bank with 98% CSAT; LHV Bank POC signed.", gap: "Compliance — Customer Operations", stage: "Series A — $13M", geo: "London, UK", finserv: "Direct production use in regulated banking. Major UK bank deployment with 98% CSAT. LHV Bank POC signed. The procedure-based / auditable / deterministic architecture is the explicit reference pattern in the BG Gap Map for how customer-operations agents should be built — exactly because it satisfies the regulatory bar without sacrificing automation depth.", team: "Founders deeper public profile not surfaced in cycle-14 search; production deployments and bank partnerships are the strongest social proof.", thesis: "Reference architecture per thesis Gap Map — not a primary scouting target since the system already understands what good looks like in this cell. The kanban_stage=talked_to (Dave has been in conversation per 2026-05-07 manual add) suggests this may convert into something more concrete. Score reflects strong gap fit + production deployment + UK regulatory environment, with the standard Series A soft-discount (upper edge of the seed-to-Series-A window). Risk: if Gradient Labs stays in customer operations rather than expanding to the marketplace governance layer, it remains a reference architecture rather than a platform-infrastructure vendor.", evidence: [["Gradient Labs — official site", "https://gradient-labs.ai/"], ["Thesis Gap Map — Compliance Customer Operations Reference Architecture", "https://github.com/dpowert2/Bene_Gesserit/blob/main/config/thesis.md"]], score: 82, bars: {gap: [30, 35], finserv: [23, 25], stage: [14, 20], team: [15, 20]}},
  {slug: "geordie", bgTeam: ["Greens"], name: "Geordie", url: "https://www.geordie.ai/", oneliner: "Agent-native security platform giving enterprises real-time discovery, behaviour monitoring, and risk control of AI agents operating across their environments. Founded by ex-Darktrace executives. $6.5M seed co-led by Ten Eleven Ventures and General Catalyst. Named Most Innovative Startup at RSAC 2026.", gap: "AI Safety & Guardrails", stage: "Seed — $6.5M", geo: "London, UK", finserv: "No named financial services customers yet, but London HQ places Geordie at the centre of the FCA-regulated market. General Catalyst (co-lead, deep finserv portfolio) provides strategic distribution into financial services. Named representative vendor in Gartners Market Guide for Guardian Agents. Revenue grew 10x in two months with secured agents increasing 10x in five months.", team: "Founded by Henry Comfort (ex-COO Americas, Darktrace), Hanah-Marie Darley (ex-Director of Security and AI Strategy, Darktrace), and Benji Weber (ex-Senior Director of Engineering, Snyk). Cybersecurity-native leadership. $6.5M seed co-led by Ten Eleven Ventures (specialist cybersecurity VC) and General Catalyst.", thesis: "Geordie occupies the guardian-agent layer — monitoring what agents do, which systems they access, and whether behaviour drifts from policy. Named Most Innovative Startup at RSAC 2026, the defining enterprise security conference. The platforms real-time agent discovery and behavioural risk intelligence directly addresses the governance requirements regulators are formalising (EU AI Act, FCA AI guidance, DORA). Manifold 5-star note Similar to Geordie — Geordie is itself a thesis archetype reference. The Darktrace pedigree means the team understands how to sell AI-powered security to risk-averse enterprises.", evidence: [["Geordie — official site", "https://www.geordie.ai/"], ["Geordie Exits Stealth with $6.5M in Seed Funding — BusinessWire", "https://www.businesswire.com/news/home/20250909556381/en/Geordie-Exits-Stealth-with-$6.5M-in-Seed-Funding-to-Give-Enterprises-Control-Over-Agentic-AI"]], score: 76, bars: {gap: [27, 35], finserv: [16, 25], stage: [18, 20], team: [18, 20]}},
  {slug: "revenium", bgTeam: ["Greens"], name: "Revenium", url: "https://www.revenium.ai/", oneliner: "AI economic control system — real-time visibility into the cost, performance, and ROI of AI operations. The first platform to produce a true profit-and-loss statement for every AI agent in production. March 2026 Tool Registry brings agent-initiated spend into a unified ledger. $13.5M Nov 2025 seed (Two Bear Capital lead, WestWave); $25.4M total.", gap: "P7 — Agent Monetisation", stage: "Seed — $13.5M Nov 2025 / $25.4M total", geo: "United States", finserv: "Direct fit for P7 Agent Monetisation — the gap currently anchored only by Paid AI as a pattern signal. Revenium goes further: not just billing for AI services but the full economic-control plane for agentic AI deployments. The P&L per agent framing is exactly what an agent marketplace needs to operationalise revenue share with third-party agent providers.", team: "John Rowell (CEO, Co-founder). John D Emic (Co-founder). Jason Cumberland (CPO, Co-founder). Investors: Two Bear Capital (Nov 2025 lead), WestWave Capital, plus earlier investors.", thesis: "Revenium occupies a thesis-aligned slot thats been thinly staffed: the economic plane underneath the agent marketplace. If the BG thesis (app store for financial agents) needs a way for institutions to pay third-party agents based on outcomes, Revenium is the closest live infrastructure. Stage signal at upper edge of gate ($25.4M total) but the most recent round is a Seed; not yet Series A. Watch for whether the customer base develops finserv-specific deployments. Manual kanban add by Dave (2026-05-07, accepted) — converted via the pending-kanban-adds flow.", evidence: [["Revenium — official site", "https://www.revenium.ai/"], ["Revenium Closes $13.5M Seed Round — Revenium (Nov 2025)", "https://www.revenium.ai/post/revenium-closes-13-5-million-seed-round-funding"], ["Revenium Launches Tool Registry — GlobeNewswire (Mar 2026)", "https://www.globenewswire.com/news-release/2026/03/03/3248056/0/en/Revenium-Launches-Tool-Registry-to-Bring-Economic-Accountability-to-AI-Agents-Deployments.html"], ["Revenium Launches AI Outcomes — Yahoo Finance", "https://finance.yahoo.com/sectors/technology/articles/revenium-launches-ai-outcomes-break-080000796.html"]], score: 72, bars: {gap: [28, 35], finserv: [14, 25], stage: [16, 20], team: [14, 20]}},
  {slug: "deeploy", bgTeam: ["Greens"], name: "Deeploy", url: "https://deeploy.ml/", oneliner: "AI governance platform that makes ML deployments accountable — embeds explainable AI (XAI) at the centre of MLOps with real-time monitoring, automatic audit trails, model-drift detection, and instant alerts for compliance risks. Open-source-framework-compatible; AWS Marketplace listing.", gap: "P5 — Audit & Explainability", stage: "Seed — €1M first investment round", geo: "Netherlands", finserv: "Direct relevance to the BG Audit & Explainability gap that has Alinia (Mouro/Santander seed) as the only first entry. Deeploys positioning — explainability + audit trails + monitoring at the heart of MLOps — is exactly what regulated finserv buyers need to satisfy why-did-the-agent-recommend-this-trade requirements. Not yet a finserv-specific play, but the architecture transfers cleanly. AWS Marketplace listing suggests enterprise sales motion.", team: "Bastiaan van de Rakt (Co-founder) — 20+ years as consultant / CEO / CTO for ML and data-science companies. Investors: Early round €1M (Curiosity Venture Capital reference; full investor list not deeply public).", thesis: "Strongest live European candidate in the Audit & Explainability cell — alongside Alinia. The thesis explicitly flags this gap as no purpose-built startup with ValidMind as the closest signal. Deeploy fits the broader pattern with European compliance-native DNA and explainable-AI-first architecture. Stage signal is clean (early seed equivalent). Risk: horizontal AI governance, not finserv-specific — the same right-architecture-wrong-vertical pattern that hurt Mindgard 2-star (AI not agents) and Goodfire 2-star. The calibration test on Deeploy is whether the agent-aware (vs model-level) story is in the product. Manual kanban add by Dave (2026-05-07, talked_to).", evidence: [["Deeploy — official site", "https://deeploy.ml/"], ["Deeploy makes AI explainable — Curiosity Venture Capital", "https://www.curiosityvc.com/post/the-deployment-of-artificial-intelligence-deeploy-makes-ai-explainable"], ["Deeploy on AWS Marketplace", "https://aws.amazon.com/marketplace/pp/prodview-7wfmblvu4dewg"], ["Deeploy — OECD.AI catalogue", "https://oecd.ai/en/catalogue/tools/deeploy"]], score: 58, bars: {gap: [24, 35], finserv: [11, 25], stage: [17, 20], team: [13, 20]}},
  {slug: "saif", bgTeam: ["Greens"], name: "SAIF Autonomy", url: "https://saifautonomy.com/", oneliner: "Trust layer for physical AI. NEXUS is a real-time guardian for AI-driven systems that monitors actions and intervenes within pre-defined rules to prevent unsafe behaviour. Customers: DSTL, Defence AI Centre, ESA, Zenzic. London-based, founded 2023. $1.2M Feb 2026 pre-seed led by Fusion Fund; $3.4M total.", gap: "P2 — AI Safety & Guardrails (adjacency caveat)", stage: "Pre-Seed — $1.2M Feb 2026 / $3.4M total", geo: "London, UK", finserv: "Adjacency caveat applies. Customer base is defence and aerospace — DSTL, DAIC, ESA, Zenzic. Successful deployments on drones and ground vehicles. No explicit financial services traction. The architectural pattern (real-time policy guardian intervening in autonomous-agent decisions) transfers conceptually to finserv but the company has not made that pivot.", team: "Kyle Thomas (CEO, Co-founder). Matthew Harris (CTO, Co-founder). Investors: Fusion Fund (Feb 2026 lead pre-seed); Cambridge Future Tech (DeepTech venture builder). Customers: DSTL, DAIC, ESA, Zenzic.", thesis: "Cleanest UK-based architectural reference for real-time policy guardian for autonomous agents — the same pattern Manifold (5-star, Similar to Geordie) and Geordie are building for digital agents. Adjacency mismatch is real and not subtle — defence / aerospace / robotics, not financial services. The Adjacency HARD GATE (G2 in calibration discipline) explicitly requires a primary financial-services fit. Track as architectural reference and watch for a pivot or finserv channel. Manual kanban add by Dave (2026-05-07, accepted) — Dave presumably sees the architectural transferability as interesting even though the vertical is wrong.", evidence: [["SAIF Autonomy — official site", "https://saifautonomy.com/"], ["SAIF Autonomy Raises $1.2M with Fusion Fund — Cambridge Future Tech", "https://www.camfuturetech.com/articles/saif-autonomy-closes-pre-seed-funding-round-led-by-fusion-fund"], ["SAIF Autonomy to use RVS to verify AI platform — Rapita Systems", "https://www.rapitasystems.com/news/saif-autonomy-use-rvs-verify-their-groundbreaking-ai-platform"]], score: 42, bars: {gap: [18, 35], finserv: [5, 25], stage: [18, 20], team: [14, 20]}},
  {slug: "trinigence", bgTeam: [], name: "Trinigence", url: "https://trinigence.com/", oneliner: "Verification pending — public press surface is thin and the site renders client-side without static content the search-terms can index. Manual kanban add by Dave (2026-05-05, accepted) — converted as a verification-pending placeholder so the manual-add discipline is auditable.", gap: "Verification pending", stage: "Verification pending", geo: "Verification pending", finserv: "Unverified. Daves manual add with kanban_stage=accepted is the strongest signal — he has presumably had a direct conversation or seen private materials that justify the accepted status. Public verification pending.", team: "Verification pending. No public LinkedIn company page surfaced this cycle.", thesis: "Placeholder pending direct verification with the operator. The kanban_stage=accepted suggests Dave has progressed past first-look on this company; the BG public-pipeline card cannot be more specific than the public press surface allows. Follow-up: add a one-line note in Turso describing the actual product / context Dave has seen, OR do a deeper LinkedIn / Crunchbase manual lookup once the company has more public press. Score 35 reflects the thinness of public verification, not the quality of the underlying signal.", evidence: [["Trinigence — official site (SPA, no static content)", "https://trinigence.com/"]], score: 35, bars: {gap: [8, 35], finserv: [5, 25], stage: [12, 20], team: [10, 20]}},
  {slug: "cognibit", bgTeam: [], name: "cogniBIT", url: "https://www.cognibit.ai/", oneliner: "Neuroscience-backed cognitive AI that models human behaviour to make autonomous systems safer — specifically for autonomous-vehicle development and testing. Driverbot product simulates human road users with virtual endurance tests for AV validation. Munich-based.", gap: "Adjacent — wrong vertical (mobility, not finserv)", stage: "Early — Grant round Jan 2021", geo: "Munich, Germany", finserv: "None. cogniBIT is a simulation and test-facility solution provider for autonomous vehicles. The vertical is mobility, not financial services. The Adjacency HARD GATE (G2) explicitly requires a primary financial-services fit; cogniBIT fails this gate cleanly.", team: "Munich-based; team profile not deeply public-facing. Investors are German innovation programmes (Werk 1, Xpreneurs, EIT KIC Urban Mobility) typical of early DeepTech in mobility.", thesis: "Carded for record-keeping, not promotion. Daves manual add with kanban_stage=rejected is the right outcome — the architectural premise (cognitive simulation of human behaviour) does not transfer cleanly to financial-services agent infrastructure, and the company has no signal of intent to pivot. Tracking as part of the discipline of converting every manual kanban add into a card so the rejection is auditable. Wrong vertical + stale stage (last documented round Jan 2021) + Adjacency HARD GATE.", evidence: [["cogniBIT — official site", "https://www.cognibit.ai/about/"], ["cogniBIT — Crunchbase", "https://www.crunchbase.com/organization/cognibit-gmbh"]], score: 25, bars: {gap: [6, 35], finserv: [2, 25], stage: [7, 20], team: [10, 20]}},
'''

NEW_DATES = '"jentic":"2026-05-07","gradient-labs":"2026-05-07","geordie":"2026-05-07","revenium":"2026-05-07","deeploy":"2026-05-07","saif":"2026-05-07","trinigence":"2026-05-07","cognibit":"2026-05-07",'

with open('startups-data.js', 'r') as f:
    content = f.read()

# Insert at top of array
ARRAY_HEADER = 'const startups = [\n'
assert ARRAY_HEADER in content
content = content.replace(ARRAY_HEADER, ARRAY_HEADER + NEW_ENTRIES, 1)

# Prepend SLUG_DATES — find first existing entry and insert before it
SLUG_DATES_PREFIX = 'const SLUG_DATES = {'
assert SLUG_DATES_PREFIX in content
content = content.replace(SLUG_DATES_PREFIX, SLUG_DATES_PREFIX + NEW_DATES, 1)

with open('startups-data.js', 'w') as f:
    f.write(content)

# Verify
import re
slugs = re.findall(r'slug: "([^"]+)"', content)
print('Total cards:', len(slugs))
for s in ['jentic','gradient-labs','geordie','revenium','deeploy','saif','trinigence','cognibit']:
    arr = s in slugs
    needle = '"{}":"2026-05-07"'.format(s)
    dates = needle in content
    print('  {}: array={} dates={}'.format(s, arr, dates))
