import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/db/client";
import { manualPending, votes } from "@/db/schema";
import { makeSlugFromAdd } from "@/lib/slug";

export const runtime = "nodejs";

const Body = z.object({
  url: z.string().url(),
  name: z.string().max(200).optional(),
});

/**
 * Submit a URL for the agent to research and turn into a BG card.
 *
 * Flow:
 *   1. Validate URL.
 *   2. Generate a stable slug (collision-resolving).
 *   3. Insert into manual_pending with status='pending'.
 *   4. Insert/update votes row to put the card in the Follow Up column immediately.
 *   5. Return 202 Accepted with the slug.
 *
 * The card itself is generated by the cron job /api/cron/process-pending,
 * which picks up rows where status='pending' and calls generateCard().
 *
 * If the deployment wants synchronous generation (waits up to ~40s), set
 * `mode: "sync"` in the body — useful for "Add and wait" UI flows.
 */
export async function POST(req: NextRequest) {
  const parsed = Body.safeParse(await req.json().catch(() => ({})));
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid body", details: parsed.error.flatten() },
      { status: 400 }
    );
  }

  let url = parsed.data.url.trim();
  if (!/^https?:\/\//i.test(url)) url = "https://" + url;

  const name = parsed.data.name?.trim() || undefined;
  const slug = await makeSlugFromAdd(url, name);
  const now = new Date().toISOString();

  await db
    .insert(manualPending)
    .values({
      slug,
      url,
      name: name ?? null,
      status: "pending",
      submittedAt: now,
    })
    .onConflictDoUpdate({
      target: manualPending.slug,
      set: { url, name: name ?? null, status: "pending", submittedAt: now, errorMsg: null },
    });

  // Put the card in the Follow Up column immediately.
  await db
    .insert(votes)
    .values({
      slug,
      voter: process.env.BG_VOTER_NAME ?? "you",
      stars: 0,
      followup: true,
      archived: false,
      kanbanStage: null,
      votedAt: now,
    })
    .onConflictDoUpdate({
      target: votes.slug,
      set: { followup: true, votedAt: now },
    });

  return NextResponse.json({ ok: true, slug, status: "pending" }, { status: 202 });
}
